---
- hosts: docker1
  gather_facts: yes

# Playbook has no tags currently but will look to add something like: 4 tags, 'build_only', 'build_and_run', 'run_only' and 'stop'

  roles:
    - role: .
    - role: create-concierge-app
    - role: create-concierge-image
    - role: create-concierge-tests
