---
- hosts: docker1
  gather_facts: yes

  pre_tasks:
    - block:
      - name: check if submodules are checked-out locally
        find:
          paths:
            - create-concierge-app/
            - create-concierge-image/
            - create-concierge-tests/
          file_type: any
        register: submodules_locally

      - name: add common roles
        shell: git submodule init && git submodule update --recursive
        register: submodule_add
        changed_when: "'checked out' in submodule_add.stdout"
        when: submodules_locally.examined == 0

      - name: stashing any local changes to common roles
        command: git submodule foreach 'git stash --all'
        register: submodule_stash
        changed_when:
          - submodule_stash.stdout != "Entering 'create-concierge-app'\nNo local changes to save\nEntering 'create-concierge-image'\nNo local changes to save\nEntering 'create-concierge-tests'\nNo local changes to save"
        when: submodules_locally.examined > 0

      - name: update common roles
        command: git submodule update --remote --recursive
        register: submodule_update
        changed_when: "'checked out' in submodule_update.stdout"
        when: submodules_locally.examined > 0

      - debug:
          msg: "UPSTREAM SUBMODULES HAVE BEEN UPDATED. PLEASE RERUN THE PLAYBOOK TO RELOAD THEM"
        when: submodule_update.changed or submodule_stash.changed
        failed_when: submodule_update.changed or submodule_stash.changed

      - debug:
          msg: "UPSTREAM SUBMODULES ADDED LOCALLY. PLEASE RERUN THE PLAYBOOK TO RELOAD THEM"
        when:
          - submodule_add is defined
          - submodule_add.changed
        failed_when: submodule_add.changed
      tags:
        - update_submodules

  roles:
    - role: .
    - role: create-concierge-app
    - role: create-concierge-image
    - role: create-concierge-tests

  post_tasks:
    - debug:
        msg: "UPSTREAM SUBMODULES HAVE CHANGED AND UPDATED LOCALLY. THE LAST RUN MAY NOT BE AFFECTED BY THESE CHANGES. PLEASE RERUN THE PLAYBOOK TO RELOAD THEM"
      when:
        - submodule_update is defined
        - submodule_update.changed
