# services is a version 2 only feature
version: '2'

services:
  server:
    image: "mesoform/concierge-consul:0.1.6"
    domainname: "consul.dockerlx.oaas.mesoform.com"
    labels:
      - triton.cns.services=consul
    restart: always
    mem_limit: 128m
    env_file:
      - _env
    network_mode: bridge
    command: >
      /usr/local/bin/consul agent -server
        -bootstrap-expect 1
        -config-dir=/etc/consul
        -ui-dir /ui
    ports:
      - 8300
      - 8301
      - 8301/udp
      - 8302
      - 8302/udp
      - 8400
      - 8500
      - 53
      - 53/udp
